behaviors:
  Walker:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 20480
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0
      gail:
        gamma: 0.99
        strength: 0.3
        demo_path: D:\georg\Documents\Master2\humanmovement\ml-agents\Project\Assets\ML-Agents\Examples\Walker\Demos\animtest1306.demo
    behavioral_cloning:
      demo_path: D:\georg\Documents\Master2\humanmovement\ml-agents\Project\Assets\ML-Agents\Examples\Walker\Demos\animtest1306.demo
      strength: 0.5
      steps: 50000
    keep_checkpoints: 5
    max_steps: 30000000
    time_horizon: 1000
    summary_freq: 30000
